<?php

return [
    'fields' => [
        'id' => 'ID',
        'branch_code' => 'Mã cơ sở',
        'branch_name' => 'Tên cơ sở',
        'request_date' => 'Ngày yêu cầu sửa chữa',
        'item_category' => 'Hạng mục',
        'issue_description' => 'Diễn giải sự cố',
        'standard_completion_time' => 'Thời gian hoàn thành',
        'severity' => 'Loại sự cố',
        'technician_name' => 'Kỹ thuật viên',
        'technician_mobile' => 'SĐT KTV',
        'technician_email' => 'Email KTV',
        'reminder' => 'Nhắc việc',
        'solution_description' => 'Khắc phục',
        'actual_completion_date' => 'Ngày hoàn thành',
        'actual_duration' => 'Thời gian Thực tế',
        'sla_status' => 'Tình trạng đáp ứng',
        'delay_reason' => 'Lý do',
        'outsourced_provider' => 'Đơn vị xử lý',
        'acceptance_result' => 'Nghiệm thu',
        'confirmed_checked' => 'Xác nhận',
        'acceptance_confirmed_by' => 'Người xác nhận',
        'created_at' => 'Ngày tạo',
        'updated_at' => 'Ngày cập nhật',
        'issue_code' => 'Mã lỗi',
        'issue_name' => 'Tên sự cố / Dịch vụ',
        'status' => 'Trạng thái',
    ],

    'tbl_fields' => [
        'stt' => 'STT',
        'branch' => 'Cơ sở',
        // 'item_category' => 'Hạng mục',
        'issue_description' => 'Diễn giải sự cố',
        // 'severity' => 'Loại sự cố',
        // 'solution_description' => 'Khắc phục',
        // 'technician' => 'Kỹ thuật viên',
        // 'sla_required' => 'Bao gồm ngày làm',
        'time' => 'Thời gian',
        // 'delay_reason' => 'Lý do',
        'status' => 'Trạng thái',
        // 'outsourced_provider' => 'Đơn vị xử lý',
        'acceptance_result' => 'Nghiệm thu',
        // 'confirmed_checked' => 'Xác nhận',
        'acceptance_confirmed_by' => 'Người xác nhận',
    ]

];